;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="ability.base.banana_boomerang",DevComment="")
GameplayTagList=(Tag="ability.base.meatball_grenade",DevComment="")
GameplayTagList=(Tag="ability.cooldown.cost",DevComment="")
GameplayTagList=(Tag="ability.cooldown.time",DevComment="")
GameplayTagList=(Tag="ability.support.jalapeno_explosion",DevComment="")
GameplayTagList=(Tag="ability.support.noodle_grapple",DevComment="")
GameplayTagList=(Tag="Character.Effects.Immunity.All",DevComment="The character is immune to all effects if true.")
GameplayTagList=(Tag="Character.Effects.Immunity.Stun",DevComment="Character is immune to stun effects if true.")
GameplayTagList=(Tag="Character.Effects.Invincibility.All",DevComment="Character cannot be killed or damaged by any source if true.")
GameplayTagList=(Tag="Character.Effects.Invincibility.Fall",DevComment="Character cannot be damaged or killed by fall damage effects.")
GameplayTagList=(Tag="Character.Effects.Invincibility.Fire",DevComment="Character cannot be damaged or killed by fire effects.")
GameplayTagList=(Tag="Character.Effects.Invincibility.Hit",DevComment="Character cannot take damage from or be killed by damaging hits.")
GameplayTagList=(Tag="Character.Effects.Invincibility.Poison",DevComment="Character cannot be damaged or killed by poison effects.")
GameplayTagList=(Tag="Character.Effects.Invincibility.Velocity",DevComment="Character cannot be damaged or killed by velocity damage effects (excludes falling, as it has its own tag)")
GameplayTagList=(Tag="Character.Effects.JustDamaged",DevComment="Whether or not the character has just been damaged.")
GameplayTagList=(Tag="Character.Effects.Stunned",DevComment="Whether or not the character has the stunned effect applied to it.")
GameplayTagList=(Tag="Character.Item.HasCritMultiplier",DevComment="")
GameplayTagList=(Tag="Character.Item.HasDamage",DevComment="")
GameplayTagList=(Tag="Character.Item.HasFireRate",DevComment="")
GameplayTagList=(Tag="Character.Item.HasHandling",DevComment="")
GameplayTagList=(Tag="Character.Item.HasMagazine",DevComment="")
GameplayTagList=(Tag="Character.Item.HasRange",DevComment="")
GameplayTagList=(Tag="Character.Item.HasScopedSpread",DevComment="")
GameplayTagList=(Tag="Character.Item.HasSpread",DevComment="")
GameplayTagList=(Tag="Character.Items.HasRange",DevComment="")
GameplayTagList=(Tag="Character.Status.Crouching",DevComment="Whether or not the character is crouching.")
GameplayTagList=(Tag="Character.Status.Equipping",DevComment="Whether or not a character is equipping/dequipping an item.")
GameplayTagList=(Tag="Character.Status.Falling",DevComment="Whether or not the character is falling.")
GameplayTagList=(Tag="Character.Status.Flying",DevComment="Whether or not the character is flying.")
GameplayTagList=(Tag="Character.Status.isDead",DevComment="Whether or not the player is dead")
GameplayTagList=(Tag="Character.Status.isPlayer",DevComment="Whether or not the character is owned by a player. If false, character is AI or not owned by a controller.")
GameplayTagList=(Tag="Character.Status.RegeneratingHealth",DevComment="Whether or not the character is regenerating health.")
GameplayTagList=(Tag="Character.Status.Reloading",DevComment="Whether or not the character is reloading a weapon.")
GameplayTagList=(Tag="Character.Status.Sprinting",DevComment="Whether or not the character is sprinting.")
GameplayTagList=(Tag="Character.Status.Swimming",DevComment="Whether or not the character is swimming.")
GameplayTagList=(Tag="Character.Status.UsingItem",DevComment="Whether or not the character is in the process of using an item.")
GameplayTagList=(Tag="DataTags.Ammunition.Pistol",DevComment="")
GameplayTagList=(Tag="DataTags.Ammunition.ReloadCount",DevComment="")
GameplayTagList=(Tag="DataTags.Ammunition.Rifle",DevComment="")
GameplayTagList=(Tag="DataTags.Ammunition.Rocket",DevComment="")
GameplayTagList=(Tag="DataTags.Ammunition.Shotgun",DevComment="")
GameplayTagList=(Tag="DataTags.Ammunition.Sniper",DevComment="")
GameplayTagList=(Tag="DataTags.Ammunition.Universal",DevComment="")
GameplayTagList=(Tag="DataTags.Item.AmmoType",DevComment="")
GameplayTagList=(Tag="DataTags.Item.CritMultiplier",DevComment="")
GameplayTagList=(Tag="DataTags.Item.Damage",DevComment="")
GameplayTagList=(Tag="DataTags.Item.Handling",DevComment="")
GameplayTagList=(Tag="DataTags.Item.Level",DevComment="")
GameplayTagList=(Tag="DataTags.Item.MagCount",DevComment="")
GameplayTagList=(Tag="DataTags.Item.MaxMagCount",DevComment="")
GameplayTagList=(Tag="DataTags.Item.MaxStackCount",DevComment="")
GameplayTagList=(Tag="DataTags.Item.Range",DevComment="")
GameplayTagList=(Tag="DataTags.Item.RateOfFire",DevComment="")
GameplayTagList=(Tag="DataTags.Item.ReloadAmt",DevComment="")
GameplayTagList=(Tag="DataTags.Item.ScopedSpread",DevComment="")
GameplayTagList=(Tag="DataTags.Item.Spread",DevComment="")
GameplayTagList=(Tag="DataTags.Item.StackCount",DevComment="")
GameplayTagList=(Tag="DataTags.OutGoingDamage",DevComment="")
GameplayTagList=(Tag="GameplayCue.HUD.UpdateEquippedWeapon",DevComment="")

